// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFlU3v2yxcQGOQsqlKa7JvGrTHr3jA4I',
    appId: '1:910146286176:web:ee52256ac895cb660b4905',
    messagingSenderId: '910146286176',
    projectId: 'cotizacionapp-a606c',
    authDomain: 'cotizacionapp-a606c.firebaseapp.com',
    storageBucket: 'cotizacionapp-a606c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpuJd2dTGtDEKEQRUp-6BLkQ2wupNWUpI',
    appId: '1:910146286176:android:c01664e9e7f6e4dc0b4905',
    messagingSenderId: '910146286176',
    projectId: 'cotizacionapp-a606c',
    storageBucket: 'cotizacionapp-a606c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6dZuSVKjoOaOps0JJV_NqbH6xon1Eq0',
    appId: '1:910146286176:ios:41a91162a11625140b4905',
    messagingSenderId: '910146286176',
    projectId: 'cotizacionapp-a606c',
    storageBucket: 'cotizacionapp-a606c.firebasestorage.app',
    iosBundleId: 'com.example.cotizacionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV6dZuSVKjoOaOps0JJV_NqbH6xon1Eq0',
    appId: '1:910146286176:ios:41a91162a11625140b4905',
    messagingSenderId: '910146286176',
    projectId: 'cotizacionapp-a606c',
    storageBucket: 'cotizacionapp-a606c.firebasestorage.app',
    iosBundleId: 'com.example.cotizacionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXFlU3v2yxcQGOQsqlKa7JvGrTHr3jA4I',
    appId: '1:910146286176:web:0754918e9bd112920b4905',
    messagingSenderId: '910146286176',
    projectId: 'cotizacionapp-a606c',
    authDomain: 'cotizacionapp-a606c.firebaseapp.com',
    storageBucket: 'cotizacionapp-a606c.firebasestorage.app',
  );
}
